#!/usr/bin/env python2.7

import os
import sys
from downloadfiles import DownloadFiles
from dszendesk import ZenDesk


def main():
    if len(sys.argv) == 2:
        ticket_id = sys.argv[1]
    else:
        sys.stderr.write('Usage: {0} <ticket_id>\n'.format(__file__))
        sys.exit(1)

    zd = ZenDesk()
    # Ensure our authentication is correct
    zd.authenticate()

    # Perform all attachment downloads
    attachments = zd.extract_file_information(ticket_id)
    dl = DownloadFiles()
    download_directory = dl.download_files(zd.download_directory, attachments)

    # Open the finder to display downloaded files
    print "\nFiles download to:\n{0}\n".format(download_directory)
    if zd.run_open:
        os.system('{0} "{1}"'.format(zd.open_program, download_directory))


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print
